[package]
name = "daemon-pki-core"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
anyhow.workspace = true
thiserror.workspace = true
serde.workspace = true
serde_json.workspace = true
uuid.workspace = true
time.workspace = true
zeroize.workspace = true
rcgen.workspace = true
x509-parser.workspace = true
